SocialApplication/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include("blogapp.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from django.urls import path
from blogapp import views
urlpatterns=[
    path("home",views.IndexView.as_view(),name="home"),
    path("accounts/signup",views.SignUpView.as_view(),name="signup"),
    path("accounts/signin",views.LoginView.as_view(),name="signin"),
    path("accounts/signout",views.sign_out,name="signout"),
    path("users/profile/add",views.CreateUserProfileView.as_view(),name="add-profile"),
    path("users/profile",views.ViewMyProfileView.as_view(),name="view-profile"),
    path("users/password/change",views.PasswordResetView.as_view(),name="password-reset"),
    path("users/profile/change/<int:user_id>",views.ProfileUpdateView.as_view(),name="profile-update"),
    path("users/profilepic/change/<int:user_id>",views.ProfilepicUpdateView.as_view(),name="profilepic-update"),
    path("posts/comment/<int:post_id>",views.add_comment,name="add-comment"),
    path("posts/like/add/<int:post_id>",views.add_like,name="add-like"),
]

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    profile_pic=models.ImageField(upload_to="profile_pics",null=True)
    bio=models.CharField(max_length=120)
    phone=models.CharField(max_length=120)
    date_of_birth=models.DateField(null=True)
    options=(
        ("male","male"),
        ("female","female"),
        ("others","others")

    )
    gender=models.CharField(max_length=12,choices=options,default="male")
    user=models.OneToOneField(User,on_delete=models.CASCADE,related_name="users")

class Blogs(models.Model):
    title=models.CharField(max_length=120)
    description=models.CharField(max_length=250)
    image=models.ImageField(upload_to="blogimages",null=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name="author")
    posted_date=models.DateField(auto_now_add=True)
    liked_by=models.ManyToManyField(User)


    @property
    def get_like_count(self):
        like_count=self.liked_by.all().count()
        return like_count

    @property
    def get_liked_user(self):
        liked_users=self.liked_by.all()
        users=[user.username for user in liked_users]
        return users

    def __str__(self):
        return self.title


class Comments(models.Model):
    blog=models.ForeignKey(Blogs,on_delete=models.CASCADE)
    comment=models.CharField(max_length=160)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

#users=[1.anj,2.django,3.python]

blogapp/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from blogapp.models import UserProfile,Blogs,Comments

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model=User
        fields=[
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        ]
class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput())

class UserProfileForm(ModelForm):
    class Meta:
        model=UserProfile
        exclude=("user",)
        widgets={
            "date_of_birth":forms.DateInput(attrs={"class":"form-control","type":"date"})
        }
class PasswordRestForm(forms.Form):
    old_password=forms.CharField(widget=forms.PasswordInput)
    new_password=forms.CharField(widget=forms.PasswordInput)
    confirm_password=forms.CharField()


class BlogForm(ModelForm):
    class Meta:
        model=Blogs
        fields=[
            "title",
            "description",
            "image"
        ]
        widgets={
            "title":forms.TextInput(attrs={"class":"form-control"}),
            "description":forms.Textarea(attrs={"class":"form-control"}),
            "image":forms.FileInput(attrs={"class":"form-control"})
        }

class ImageResetForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = [
            "profile_pic"
        ]
        widgets = {
            "profile_pic": forms.FileInput(attrs={"class": "form-control"})
        }

class CommentForm(ModelForm):
    class Meta:
        model=Comments
        fields=[
            "comment"
        ]
        widgets={
            "comment":forms.TextInput(attrs={"class":"form-control"})

        }

blogapp/views.py
from django.shortcuts import render,redirect
from django.views.generic import View,CreateView,FormView,TemplateView,UpdateView
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.models import User
from blogapp.forms import UserRegistrationForm,LoginForm,UserProfileForm,PasswordRestForm,BlogForm,CommentForm,ImageResetForm
from django.contrib import messages
from django.urls import reverse_lazy
from blogapp.models import UserProfile,Blogs,Comments

# Create your views here.

# def index(request):
#     return render(request,"base.html")

class SignUpView(CreateView):
    form_class=UserRegistrationForm
    template_name="registration.html"
    model=User
    success_url = reverse_lazy("signin")

    # def get(self,request,*args,**kwargs):
    #     form=self.form_class()
    #     return render(request,self.template_name,{"form":form})
    #
    # def post(self,request,*args,**kwargs):
    #     form=self.form_class(request.POST)
    #     if form.is_valid():
    #         form.save()
    #         messages.success(request, "Registration successfull")
    #         return redirect("signup")
    #     else:
    #         messages.error(request, "Failed")
    #         return render(request,self.template_name,{"form":form})

class LoginView(FormView):
    model=User
    form_class=LoginForm
    template_name="login.html"

    # def get(self,request,*args,**kwargs):
    #     form=self.form_class()
    #     return render(request,self.template_name,{"form":form})
    def post(self,request,*args,**kwargs):
        form=self.form_class(request.POST)
        if form.is_valid():
            uname=form.cleaned_data.get("username")
            pwd=form.cleaned_data.get("password")
            user=authenticate(request,username=uname,password=pwd)
            if user:
                login(request,user)
                print("success")
                return redirect("home")
            else:
                messages.error(request,"invalid credentials")
                return render(request,self.template_name,{"form":form})

class IndexView(CreateView):
    model= Blogs
    form_class=BlogForm
    success_url=reverse_lazy("home")
    template_name = "home.html"

    def form_valid(self,form):
        form.instance.author=self.request.user
        self.object=form.save()
        messages.success(self.request,"post has been saved")
        return super().form_valid(form)
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        blogs=Blogs.objects.all().order_by("-posted_date")
        context["blogs"]=blogs
        comment_form=CommentForm()
        context["comment_form"]=comment_form
        return context


class CreateUserProfileView(CreateView):
    model = UserProfile
    template_name = "add-profile.html"
    form_class = UserProfileForm
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.instance.user=self.request.user
        messages.success(self.request,"profile has been created")
        self.object=form.save()
        return super().form_valid(form)

class ViewMyProfileView(TemplateView):
    template_name = "view-profile.html"

class PasswordResetView(FormView):
    template_name = "passwordreset.html"
    form_class = PasswordRestForm
    def post(self, request, *args, **kwargs):
        form=self.form_class(request.POST)
        if form.is_valid():
            oldpassword=form.cleaned_data.get("old_password")
            password1=form.cleaned_data.get("new_password")
            password2=form.cleaned_data.get("confirm_password")
            user=authenticate(request,username=request.user.username,password=oldpassword)
            if user:
                user.set_password(password2)
                user.save()
                messages.success(request,"password changed")
                return redirect("signin")
            else:
                messages.error(request,"invalid credentials")
                return render(request,self.template_name,{"form":form})

class ProfileUpdateView(UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = "profile-update.html"
    success_url = reverse_lazy("home")
    pk_url_kwarg = "user_id"

    def form_valid(self, form):
        messages.success(self.request,"Your Profile has been updated successfully")
        self.object = form.save()
        return super().form_valid(form)

class ProfilepicUpdateView(UpdateView):
    model = UserProfile
    form_class = ImageResetForm
    template_name = "profilepic-update.html"
    success_url = reverse_lazy("home")
    pk_url_kwarg = "user_id"

    def form_valid(self, form):
        messages.success(self.request, "Your Profile has been updated successfully")
        self.object = form.save()
        return super().form_valid(form)



def add_comment(request,*args,**kwargs):
    if request.method=="POST":
        blog_id=kwargs.get("post_id")
        blog=Blogs.objects.get(id=blog_id)
        user=request.user
        comment=request.POST.get("comment")
        Comments.objects.create(blog=blog,user=user,comment=comment)
        messages.success(request,"comment has been posted")
        return redirect("home")

def add_like(request,*args,**kwargs):
    blog_id=kwargs.get("post_id")
    blog=Blogs.objects.get(id=blog_id)
    blog.liked_by.add(request.user)
    blog.save()
    return redirect("home")


def sign_out(request,*args,**kwargs):
    logout(request)
    return redirect("signin")

blogapp/templates/add-profile.html
{%extends 'base.html'%}
{%block body_block%}
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            {%if messages%}
            {%for msg in messages%}
            {%if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS%}
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                <strong>Holy guacamole!</strong> {{msg}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {%endif%}
            {%if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Holy guacamole!</strong> {{msg}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {%endif%}
            {%endfor%}
            {%endif%}
            <form action="" method="post" enctype="multipart/form-data">
                {%csrf_token%}
                {{form.as_p}}
                <button type="submit">submit</button>
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>



{%endblock%}

blogapp/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Blog Post - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{%static 'assets/favicon.ico'%}"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{%static 'css/styles.css'%}" rel="stylesheet"/>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

</head>
<body style="background-image:url({%static 'assets/pic3.jpg'%});color:white;width:100%;height:100%;">
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#!">Blog Spot</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" href="{%url 'home'%}">Home</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        ManageProfile
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li class="nav-item">
                            {%if request.user.users%}
                            <a href="{%url 'view-profile'%}" class="dropdown-item">ViewMyProfile</a>
                            {%else%}
                            <a href="{%url 'add-profile'%}" class="dropdown-item">AddProfile</a>
                            {%endif%}
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{%url 'password-reset'%}">Change Password</a></li>
                        <li><a class="dropdown-item" href="{%url 'profile-update' request.user.users.id%}">Update
                            Profile</a></li>
                        <li class="nav-item"><a class="dropdown-item" href="{%url 'signout'%}">Logout</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a class="nav-link" href="#!">About</a></li>

                <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">{{request.user}}</a></li>
                <div style="width:100%;height:100%;">
                    {%if request.user.users.profile_pic%}
                    <li class="nav-item" ><a href="{%url 'profilepic-update' request.user.users.id%}"><img
                            src="{{request.user.users.profile_pic.url}}" alt="..." class=""

                            style="width:50px;height:50px;"></a>
                        {%endif%}
                    </li>
                </div>
        </div>
        </ul>
    </div>
    </div>
</nav>
{%if messages%}
{%for msg in messages%}
{%if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS%}
<div class="alert alert-info alert-dismissible fade show" role="alert">
    <strong>Holy guacamole!</strong> {{msg}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{%endif%}
{%if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Holy guacamole!</strong> {{msg}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{%endif%}
{%endfor%}
{%endif%}
<body>
<div class="container">
    {%block body_block%}

    {%endblock%}
</div>
</body>


<!-- Core theme JS-->
<!-- JavaScript Bundle with Popper -->
</body>

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</html>

blogapp/templates/home.html
{%extends 'base.html'%}
{%block body_block%}
<br>
<h1 style="text-align:center;">Welcome user {{request.user}}</h1>
<div class="row">
    <div class="col-4">
        <div class="accordion accordion-flush border border-4 border-dark" id="accordionFlushExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                        <p class="font-weight-bold">Create New Blog</p>
                    </button>
                </h2>
                <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne"
                     data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        <form action="" method="post" enctype="multipart/form-data">
                            {%csrf_token%}
                            {{form.as_p}}
                            <button type="submit">submit</button>

                        </form>

                    </div>
                </div>
            </div>
        </div>

    </div>
    <!--    <div class="col-4">-->
    <!--    </div>-->
    <div class="col-8 mt-3">
        <h2 style="text-align:center;">Blogs</h2>
        {%for blog in blogs%}
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8 border border-white mt-3">
                <p class="fw-bold bg-dark mt-3" style="color:white;text-align:center;">{{blog.title}}</p>
                {%if blog.image%}
                <img src="{{blog.image.url}}" class="img-fluid" alt="">
                <p>posted by {{blog.author}}</p>
                <p>created_at {{blog.posted_date}}</p>
                <form action="{%url 'add-comment' blog.id%}" method="post">
                    {%csrf_token%}
                    {{comment_form.as_p}}
                    <button type="submit">submit</button>
                </form>
                <a href="{%url 'add-like' blog.id%}">Like</a>
                {{blog.get_like_count}}
                {%for user in users%}
                    {{blog.get_liked_user}}
                {%endfor%}
                {%endif%}
                {%for comment in blog.comments_set.all%}
                <div class="mt-3">
                    <pre><img style="width:50px;height:50px; border-radius:50%;" src="{{comment.user.users.profile_pic.url}}" alt="..."
                             class=""> {{comment.user}} - {{comment.comment}} </pre>
                </div>
                <div><span></span></div>
                {%endfor%}
            </div>
            <div class="col-2"></div>
        </div>
        {%endfor%}
    </div>
</div>
<div class="row bg-dark mt-3">
    <div class="col-4"></div>
    <div class="col-4">
        <p style="text-align:center; color:white;">Copyright(c)</p>
    </div>
    <div class="col-4"></div>
</div>

{%endblock%}

blogapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<body>
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">

        {%if messages%}
        {%for msg in messages%}
        {%if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS%}
        <div class="alert alert-info alert-dismissible fade show" role="alert">
            <strong>Holy guacamole!</strong> {{msg}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {%endif%}
        {%if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Holy guacamole!</strong> {{msg}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {%endif%}
        {%endfor%}
        {%endif%}
    </div>
    <div class="col-4"></div>
</div>
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <section class="vh-100 gradient-custom">
            <div class="container py-5 h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12">
                        <div class="card bg-dark text-white" style="border-radius: 1rem;">
                            <div class="card-body p-5 text-center">

                                <div class="mb-md-5 mt-md-4 pb-5">

                                    <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                                    <p class="text-white-50 mb-5">Please enter your login and password!</p>

                                    <form action="" method="post">
                                        {%csrf_token%}
                                        {{form.as_p}}
                                        <button type="submit">submit</button>
                                    </form>

                                    <p class="small mb-5 pb-lg-2"><a class="text-white-50" href="#!">Forgot
                                        password?</a></p>


                                    <div class="d-flex justify-content-center text-center mt-4 pt-1">
                                        <a href="#!" class="text-white"><i class="fab fa-facebook-f fa-lg"></i></a>
                                        <a href="#!" class="text-white"><i
                                                class="fab fa-twitter fa-lg mx-4 px-2"></i></a>
                                        <a href="#!" class="text-white"><i class="fab fa-google fa-lg"></i></a>
                                    </div>

                                </div>

                                <div>
                                    <p class="mb-0">Don't have an account? <a href="#!" class="text-white-50 fw-bold">Sign
                                        Up</a>
                                    </p>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>


    </div>
    <div class="col-4"></div>
</div>
</body>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</html>

blogapp/templates/passwordreset.html
{%extends 'base.html'%}
{%block body_block%}
<br>
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            {%if messages%}
            {%for msg in messages%}
            {%if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS%}
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                <strong>Holy guacamole!</strong> {{msg}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {%endif%}
            {%if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Holy guacamole!</strong> {{msg}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {%endif%}
            {%endfor%}
            {%endif%}
            <form action="" method="post" enctype="multipart/form-data">
                {%csrf_token%}
                {{form.as_p}}
                <button type="submit">submit</button>
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>



{%endblock%}

blogapp/templates/profile-update.html
{%extends 'base.html'%}
{%block body_block%}
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">

            <h1>Update Profile</h1>
            <form action="" method="post" enctype="multipart/form-data">
                {%csrf_token%}
                {{form.as_p}}
                <button type="submit">submit</button>
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>



{%endblock%}

blogapp/templates/profilepic-update.html
{%extends 'base.html'%}
{%block body_block%}
<br>
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            {%if messages%}
            {%for msg in messages%}
            {%if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS%}
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                <strong>Holy guacamole!</strong> {{msg}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {%endif%}
            {%if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Holy guacamole!</strong> {{msg}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {%endif%}
            {%endfor%}
            {%endif%}
            <form action="" method="post" enctype="multipart/form-data">
                {%csrf_token%}
                {{form.as_p}}
                <button type="submit">submit</button>
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>



{%endblock%}

blogapp/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<body>
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">

            {%if messages%}
            {%for msg in messages%}
            {%if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS%}
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                <strong>Holy guacamole!</strong> {{msg}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {%endif%}
            {%if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Holy guacamole!</strong> {{msg}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {%endif%}
            {%endfor%}
            {%endif%}
    </div>
    <div class="col-4"></div>
</div>
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="post">
                {%csrf_token%}
                {{form.as_p}}
                <button type="submit">submit</button>
            </form>

        </div>
        <div class="col-4"></div>
    </div>
</body>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</html>

blogapp/templates/view-profile.html
{%extends 'base.html'%}
{%block body_block%}
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <div class="card" style="width: 18rem;">
  <img src="{{request.user.users.profile_pic.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title" style="color:black;">{{request.user}}</h5>
    <p class="card-text" style="color:black;">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Phone {{request.user.users.phone}}</li>
    <li class="list-group-item">DOB {{request.user.users.date_of_birth}}</li>
    <li class="list-group-item">A third item</li>
  </ul>
  <div class="card-body">
    <a href="#" class="card-link">Follow</a>
    <a href="{%url 'profile-update' request.user.users.id%}" class="card-link">Update Profile</a>
  </div>
</div>
    </div>
    <div class="col-4"></div>
</div>

{%endblock%}